# Generated by Django 3.2.9 on 2022-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='nmber',
            new_name='number',
        ),
    ]
